version: 2.1
orbs:
  go: gotest/tools@0.0.9
  codecov: codecov/codecov@1.0.2

executors:
  dockerizer:
    docker:
      - image: cimg/go:1.15.2
    environment:
      IMAGE_NAME: filecoin/sentinel-visor
  golang:
    docker:
      - image: circleci/golang:1.13

commands:
  install-deps:
    steps:
      - go/install-ssh
      - go/install: {package: git}
  prepare:
    parameters:
      linux:
        default: true
        description: is a linux build environment?
        type: boolean
    steps:
      - checkout
      - when:
          condition: << parameters.linux >>
          steps:
            - run: sudo apt-get update
      - run: git submodule sync
      - run: git submodule update --init
  build-docker-and-maybe-push:
    parameters:
      tagname:
        description: docker tag name with which to build and push
        type: string
        default: $CIRCLE_TAG
      push:
        description: whether to push created docker image after build
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker:
          version: "18.09.3"
      - run:
          name: Build Dev Docker image
          command: docker build -t ${IMAGE_NAME}-dev -f Dockerfile.dev .
      - run:
          name: Build Production Docker image
          command: docker build -t $IMAGE_NAME -f Dockerfile .
      - when:
          condition: << parameters.push >>
          steps:
            - run:
                name: Publish Dev Docker Image to Docker Hub
                command: |
                  echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                  ./scripts/push-docker-tags.sh "${IMAGE_NAME}-dev" "$CIRCLE_SHA1" "$CIRCLE_BRANCH" "<< parameters.tagname >>-dev"
            - run:
                name: Publish Production Docker Image to Docker Hub
                command: |
                  echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                  ./scripts/push-docker-tags.sh "$IMAGE_NAME" "$CIRCLE_SHA1" "$CIRCLE_BRANCH" "<< parameters.tagname >>"
  lint: &lint
    description: |
      Run golangci-lint.
    parameters:
      executor:
        type: executor
        default: golang
      golangci-lint-version:
        type: string
        default: 1.27.0
      concurrency:
        type: string
        default: '2'
        description: |
          Concurrency used to run linters. Defaults to 2 because NumCPU is not
          aware of container CPU limits.
      args:
        type: string
        default: ''
        description: |
          Arguments to pass to golangci-lint
    executor: << parameters.executor >>
    steps:
      - install-deps
      - prepare
      - run:
          command: make deps
          no_output_timeout: 30m
      - go/install-golangci-lint:
          gobin: $HOME/.local/bin
          version: << parameters.golangci-lint-version >>
      - run:
          name: Lint
          command: |
            $HOME/.local/bin/golangci-lint run -v --timeout 2m \
              --concurrency << parameters.concurrency >> << parameters.args >>
  lint-all:
    <<: *lint

jobs:
  build-push-master:
    executor: dockerizer
    steps:
      - build-docker-and-maybe-push:
          push: true
          tagname: master-latest
  build-push-semver-tag:
    executor: dockerizer
    steps:
      - build-docker-and-maybe-push:
          push: true
          # use default tagname
  mod-tidy-check:
    executor: golang
    steps:
      - install-deps
      - prepare
      - go/mod-tidy-check
  test:
    docker:
      - image: cimg/go:1.15.2
      - image: timescale/timescaledb:1.7.4-pg12
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: # dep for DB wait script
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: sudo apt-get update
      - run: sudo apt-get install -y pkg-config jq
      - run: make deps
      - run: make build
      - run:
          name: waiting for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: 
          name: installing schema
          command: ./visor migrate --latest
          environment:
            LOTUS_DB: postgres://postgres:password@localhost:5432/postgres?sslmode=disable
      - run:
          command: |
            make test-coverage
            mkdir -p /tmp/artifacts
            mv coverage.out /tmp/artifacts/coverage.out
      - codecov/upload:
          file: /tmp/artifacts/coverage.out
      - store_artifacts:
          path: sentinel-visor

workflows:
  version: 2
  check:
    # `test` and `mod-tidy-check` runs for all branches
    jobs:
      - mod-tidy-check
      - lint-all:
          concurrency: "16"   # expend all docker 2xlarge CPUs.
      - test
  docker-and-deploy:
    # `build-push-*` runs on master or main branches and tags that look like semver
    # see: https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
    jobs:
      - build-push-master:
          # build and push latest master docker image
          filters:
            branches:
              only: /^(master|main)$/
            tags:
              ignore: /.*/
      - build-push-semver-tag:
          # build and push semver tags docker image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)*/  # incl v0.0.0 or v0.0.0-rc0

